name: Sample Inputs 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: environment
      customObject:
        description: Input Body
        required: true
        type: string
      entityPicker:
        description: Select an entity
        required: true
        type: choice
        options:
          - EntityA
          - EntityB
          - EntityC
      

jobs:
  sample_input_runner:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Display Output
        run: |
          echo "| Environment         | ${{ inputs.environment }}|"
          echo "| Input Object        | ${{inputs.customObject }}|"
          echo "| Selected Entity     | ${{ inputs.entityPicker }}|"

